### PR TITLE
(Fix) Show error when position is not found

### LINKED ISSUE #578: [prod/stage/dev] Empty screen is displayed on a position details page when there is no such position
1. Open a position details in the Rinkeby
2. Switch to the Mainnet 

**AR:** empty screen is displayed

**ER:** show 'Not found' error at least (as it is shown on a condition details page)

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #578

Not sure about how correct the code to check if the position exists is (no errors where being pushed when a position wasn't found), but it seems to do the trick.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr586--conditionaltokensexplorer.review.gnosisdev.com

File: src/contexts/PositionContext.tsx [hunk 1]
```diff
@@ -75,14 +75,17 @@ export const PositionProvider = (props: Props) => {
...
       position = positionFromTheGraph
     } else {
       errors.push(PositionErrors.NOT_FOUND_ERROR)
     }
   }
 
+  if (positionId && !position && !loading) {
+    errors.push(PositionErrors.NOT_FOUND_ERROR)
+  }
+
```
Comment (hpmaxi) [inline src/contexts/PositionContext.tsx:88]: The first `if` is checking for a position and then checking if it is null (that is impossible because otherwise, it would never enter that branch).

So lines 76-77 can be written as
```
 if (positionId && fetchedPosition) {
    const { position: positionFromTheGraph } = fetchedPosition
``` 

Another solution is to maintain the new `if` and left the other as

```
if(positionId && fetchedPosition?.position) {
    position = fetchedPosition?.position
}
```

I didn't tested this last alternative but I know that `fetchedPosition` will be undefined (if the query is not loaded) or `{ position: PositionObject | null }`, so the only way that `fetchedPosition?.position` were true is with the object having the PositionObject inside.

**Review by hpmaxi — CHANGES_REQUESTED** [review]

**Comment by elena-zh** [comment]
The changes look goo to me

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr586--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]
