### PR TITLE
Remove get provider name web3modal from `getWalletName`

### LINKED ISSUE #216: Incorrect (metamask) connection method is displayed when connect to the app using walletconnect
**Steps:** 
1. Click on the 'Connect to Wallet' button
2. Select WalletConnect
3. Successfully complete the action
4. Expand the dropdown with connection info

**Actual Result:** connection method is Metamask

**Expected Result:** connection method is WalletConnect

### PR DESCRIPTION
**Pull request by davidalbela**
Closes #216

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr291--conditionaltokensexplorer.review.gnosisdev.com

File: src/components/common/UserDropdown/index.tsx [hunk 1]
```diff
@@ -139,9 +138,8 @@ const getNetworkName = (data: Connected): string => {
 }
 
 const getWalletName = (data: Connected): string => {
-  const injectedName = getInjectedProviderName()
-  const provider = getProviderInfo(data.provider)
-  return injectedName || provider.name
+  const isMetaMask = data.provider._web3Provider && data.provider._web3Provider.isMetaMask
+  return isMetaMask ? 'MetaMask' : 'WalletConnect'
```
Comment (hpmaxi) [inline src/components/common/UserDropdown/index.tsx:142]: If we add a provider in the future this will break. I think `provider.name` isn't configured correctly or something like that.

**Review by hpmaxi — CHANGES_REQUESTED** [review]

File: src/components/common/UserDropdown/index.tsx (hunk 1 above)
Comment (mariano-aguero) [reply src/components/common/UserDropdown/index.tsx:142]: I saw that _chrome dev tools_ detects the type of the object properly
Screenshot_20200918_161545

How to check type guards ? see https://www.typescriptlang.org/docs/handbook/advanced-types.html for more information.

If we don't get a solution for this, we will need to apply the null conditional operator (aka elvis operator ?) to check the deep properties of the object

**Review by mariano-aguero — COMMENTED** [review]
See comments

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr291--conditionaltokensexplorer.review.gnosisdev.com

**Review by hpmaxi — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]
