### PR TITLE
Make impossible to merge positions using using conditions of shallower positions 

### LINKED ISSUE #611: Transaction fails when merge positions with more that 2 conditions
Related to #598, #512, #571

Here are the steps: 
condition 1  - 0x036b8db48aebd17d8dae014e37e2db03af33137f1ce80a7f172bc251da3b6bac
with 3 positions: 
	C1 position 1  0x2269228c44ceaed9cdcb0622e2532b38f8eb642f4a59b230ecdbf66e3c306175
	C1 position 2  0x65669480d9f418fbe7a59c2f80cdd6703639f593ae5ff38e00b12fc127ee40d8
	C1 position 3  0xa432aadacd0d09c3f5c29b131d652dd6a96c5ad4d9cc809c2b7d360fcdf8256a
	
	
Condition 2 with 4 outcomes: 0xaf8ec4afa7df9b46cea10cfdcfab35cf1a6b5d00e0427fcb0e3eef1504caac4e

I split position C1P1 under the condition 2 and get 4 positions: 0x2269228c44ceaed9cdcb0622e2532b38f8eb642f4a59b230ecdbf66e3c306175
c2c1p1  0xe250eeef9da04a71368551b53711d50d3cf5414aa4dd6510408956f17ed90f33
c2c1p2  0x31f767a2bc40ff4303d77168d926e5fecc1b16fecc1f950c7eeb25f99ef4cc5a 
c2c1p3  0x56e3d22c0933b150c66c42b3d1250a5e9f837f4054567a8d90aaaee860c0354e
c2c1p4  0x4bf76be278029414b3958549ec4c1d7204e2fa6cc9beb43412d7ed453e5a41ce

Condition 1 details: 

Condition 2 details: 

**merge c2c1p1**  0xe250eeef9da04a71368551b53711d50d3cf5414aa4dd6510408956f17ed90f33 
with **c2c1p3**  0x56e3d22c0933b150c66c42b3d1250a5e9f837f4054567a8d90aaaee860c0354e  under  **condition C1** ---> transaction fails
 
c1 error https://rinkeby.etherscan.io/tx/0xb4d21aecbd0fad263d50e4dc2e8191baa687aa8cf1dd0b88732c5bb5c8642583

**merge c2c1p1**  0xe250eeef9da04a71368551b53711d50d3cf5414aa4dd6510408956f17ed90f33 
with **c2c1p3**  0x56e3d22c0933b150c66c42b3d1250a5e9f837f4054567a8d90aaaee860c0354e  under  **condition C2** ---> transaction fails

c2 error https://rinkeby.etherscan.io/tx/0x7d228b2b39cfc2dd73b3f8972133fd168220fafc75c919fd10f6b7f89c5f2ed2

**Expected Result:** positions c2c1p1 - c2c1p4 should be merged under  **condition C2* 
 and cannot me merged with condition c1 (as it was in the previous app version)
So, when a user selects the condition 2 to merge, 'Merge' button should be enabled and the transaction should be successful
When a user selects the condition 1 to merge, 'Merge' button should be disabled.

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #611 

I was able to merge without any changes for the base case (positions c2c1p1 - c2c1p4 merged by c2), I just filtered conditions to avoid showing conditions shared in shallower positions.

For the record, the problem was that if you have a condition C1, and split it like this
``` 
$:C1:O1 (C1-P1)
$:C1:O2 (C1-P2)
```

The indexSet of C1-P1 will be `[1]` and for C1-P2 will be `[2]`, in both cases the conditionsIds will be [C1]

If we split again, using C1-P2, with C2 for example of 4 outcomes, we will get
```
C1-P2:C2:O1 [2 1] [C1 C2]
C1-P2:C2:O2 [2 2] [C1 C2]
C1-P2:C2:O3 [2 4] [C1 C2]
C1-P2:C2:O4 [2 8] [C1 C2]
```

And then we try to merge any number >= 2 of positions from that set using C1, we will get a partition with the form of [2 2] or [2 2 2], etc. This is a disjoint partition. With the extra filter, in the dropdown, we only show C2.

Also, this should improve the situation of #612, the problem is that for the graph conditionsIds is an array and the indexSets is a set, so if we in the previous example use again C1, what we would obtain is something like

```
C1-P2:C1:O1 [2 1] [C1 C1]
C1-P2:C1:O2 [2] [C1 C1]
```

Because we can't have in an indexSet field a `[2 2]`. 

For a real case, in rinkeby.

```
  p1: position(id: "0x70996f31153f38815a33a62550672c4694d67c202afbb776733f805bf0010afc") {
    indexSets
    conditionIds
  }
  p2: position(id: "0x201bbf0ee7f77ed43e31b94f8172ceede684a409144a68206b6ad5f0426bcdb1") {
    indexSets
    conditionIds
  }
  p3: position(id: "0xa2887462a95f9499cff7c5e099344805780880b0d8f1cf47c958eced7640e55d") {
    indexSets
    conditionIds
  }
}
```

p1 and p2 can't be merged with anything, and p3 is compatible with shallower positions (and can be merged successfully), I think we must avoid positions that are recursive, or with cycles. Or find a solution in the graph side, with the data received there no much more that can be done to avoid this.

### CODE REVIEW

File: src/pages/MergePositions/Contents.tsx [hunk 1]
```diff
@@ -264,31 +265,33 @@ export const Contents = () => {
...
-            !positionWithBalance.userBalanceERC1155.isZero() &&
-            //#2 Filter, remove original selected position
-            positionWithBalance.id.toLowerCase() !== position.id.toLowerCase() &&
-            //#3 Filter, positions with the same condition set
-            positionWithBalance.conditionIds.sort().join('') ===
-              position.conditionIds.sort().join('') &&
-            //#4 Filter, positions with the same collateral
-            positionWithBalance.collateralToken.toLowerCase() ===
-              position.collateralToken.toLowerCase()
-        )
```
Comment (hpmaxi) [inline src/pages/MergePositions/Contents.tsx:289]: arePositionMergeablesByCondition was doing the same. Seems like something that was left from a merge.

File: src/pages/MergePositions/Contents.tsx [hunk 2]
```diff
@@ -264,31 +265,33 @@ export const Contents = () => {
...
+
+        const conditionIds: string[] = conditionsOfSelectedPosition
+          .map((c) => c.conditionId)
+          .filter((conditionId) => {
+            return positionsMergeables.some((p) => {
+              return indexSetsByCondition(p)[conditionId] !== indexSetsOfConditions[conditionId]
+            })
+          })
+        // Remove duplicates
+        const possibleConditions = lodashUniq(conditionIds)
```
Comment (hpmaxi) [inline src/pages/MergePositions/Contents.tsx:293]: This was moved up because of the types of the positions list used to that point. Can be extracted to a function in tools but I don't know how to name it yet

File: src/util/tools.ts [hunk 3]
```diff
@@ -193,8 +194,7 @@ export const getRedeemedPreview = (
 
 export const positionsSameConditionsSet = (positions: PositionWithUserBalanceWithDecimals[]) => {
   // all postions include same conditions set and collateral token
-  const conditionIdsSet = positions.map((position) => [...position.conditionIds].sort().join(''))
-  return conditionIdsSet.every((set) => set === conditionIdsSet[0])
+  return positions.every((position) => isEqual(position.conditionIds, positions[0].conditionIds))
```
Comment (hpmaxi) [inline src/util/tools.ts:197]: That was difficult to read and we have `isEqual` in the dependencies anyways.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr618--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]
