### PR TITLE
Fix Split Position unassigned collateralToken from a given positionId

### LINKED ISSUE #361: [FE] Incorrect collateral token (DAI) is displayed when split a position that is not in default collateral (USDC)
When I split a position in USDC, as an example, I get the confirmation pop-up with DAI collateral on it and with 0 amount. 

However, the positions have the correct ID, show the correct collateral and amount on their details

**Expected Result:** show the collateral and amount which corresponds to the position collateral.

### PR DESCRIPTION
**Pull request by davidalbela**
After split a position from a given position id, the constant set to alias from `collateral` is already an assinged constant. Typescript and linter are not warning about that because the alias comes with double asignation. Maybe could be reported to the linter.

Closes #361

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr400--conditionaltokensexplorer.review.gnosisdev.com

File: src/pages/SplitPosition/Form.tsx [hunk 1]
```diff
@@ -172,11 +172,8 @@ export const Form = ({
...
           )
         } else if (splitFromPosition && position) {
-          const {
-            collateralToken: { id: collateral },
-            collection: { id: collectionId },
-          } = position
-
+          collateral = position.collateralToken?.id
+          const collectionId = position.collection?.id
           await splitPosition(collateral, collectionId, conditionId, partition, amount)
```
Comment (hpmaxi) [inline src/pages/SplitPosition/Form.tsx:177]: I could be missing something here, but to me seems that the problem was caused by the use of  `collateral` instead of `collateralToken` and `collectionId` instead of `collection`.  I prefer to change that if for `splitFromPosition && position && position.collateralToken && position.collection` and make the destructuring as it was done before but changing the call to `splitPosition`.



This could also be fixing #289, can you check that?

**Review by hpmaxi — CHANGES_REQUESTED** [review]

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr400--conditionaltokensexplorer.review.gnosisdev.com

File: src/pages/SplitPosition/Form.tsx (hunk 1 above)
Comment (davidalbela) [reply src/pages/SplitPosition/Form.tsx]: Added `collateralFromSplit` to the PR.

**Review by hpmaxi — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]
