### PR TITLE
(Fix) Add "Prepare Omen Condition" date warning

### LINKED ISSUE #429: Warning message about the resolution date should be displayed when a user creates an Omen condition
See how it is designed in Omen: 

However, user still should be allowed to create a condition with a resolution date in the past...

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #429

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr462--conditionaltokensexplorer.review.gnosisdev.com

File: src/pages/PrepareCondition/index.tsx [hunk 1]
```diff
@@ -529,6 +533,14 @@ export const PrepareCondition = () => {
                   </>
                 }
               />
+              <StatusInfoInline status={StatusInfoType.warning}>
+                Set the market resolution date at least 6 days after the correct outcome will be
+                known and make sure that this market won&apos;t be{' '}
+                <Link href="https://conditional.netlify.app/rules.pdf" target="_blank">
```
Comment (hpmaxi) [inline src/pages/PrepareCondition/index.tsx:539]: This could be a constant in the future?.

**Review by hpmaxi — APPROVED** [review]

**Review by mariano-aguero — APPROVED** [review]
