### PR TITLE
[FE] Conditions List Filters

### LINKED ISSUE #392: Resolution date for Omen conditions is incorrect
All Omen conditions show a resolution date of `1970-01-01 - 00:00 UTC`.
image

### LINKED ISSUE #408: [FE] Conditions List Search Items
Related to https://github.com/gnosis/conditional-tokens-explorer/issues/337 and https://github.com/gnosis/conditional-tokens-explorer/issues/341#issuecomment-700259206

**Design:** https://zpl.io/awKqdB1 - https://zpl.io/VDLZ6lr

The user should be able to search by:

- All (includes all of the next items).
- Condition Id
- Question Id
- Oracle Address
- Reporting Address
- Condition Creator Address

### LINKED ISSUE #410: [FE] Conditions List Filters
Related to https://github.com/gnosis/conditional-tokens-explorer/issues/337 and https://github.com/gnosis/conditional-tokens-explorer/issues/341#issuecomment-700259206

**Design:** https://zpl.io/awKqdB1 - https://zpl.io/VDLZ6lr

The user should be able to filter by:

- Reporter / Oracle: All / Current Wallet / Custom Reporters / Realit.io / Kleros
- Status: All / Open / Resolved
- Condition Type: All / Custom Reporter / Omen Condition
- Number of Outcomes: A min / max range.
- Creation Date: A from / to range.
- Validity: All / Valid / Invalid (this is for Omen Conditions, check https://omen.eth.link/rules.pdf)

Hiding the filters' column should clear the filters.

### LINKED ISSUE #428: Omen condition is displayed as a Custom Reporter after its creation
Related to #415, #304

1. Open Prepare Condition page
2. Select Omen condition
3. fill in all the fields
4. Click on the 'Prepare' button and confirm all the transactions
5. Press on the OK button on the successful pop-up

**Actual result:** user is redirected to the conditions details. 
However, Omen condition is displayed as a Custom Reporter after its creation

**Expected Result:** omen condition should be displayed as an Omen condition and should display all the condition details.
Something like:

### LINKED ISSUE #430: Omen condition: 'Prepare' button is enabled, user is allowed to create an Omen condition with <2 outcome
Related to #415, #304

**Steps:** 
1. Open prepare condition page
2. Select Omen condition
3. Fill in all the required fields
4. Fill in the Outcomes section with only 1 outcome(or NO outcomes at all)
5. Click on the 'Prepare' button

**Actual Result:** 'Prepare' button is enabled, user is allowed to create an Omen condition with only 1 outcome

**Expected Result:**  'Prepare' button is disabled. user is not allowed to create a condition with 1 outcome

### LINKED ISSUE #435: Prepare Omen condition:  System allows to create a condition with the question and outcomes which are already exist
I have created exactly the same Omen condition (except the date - the system does not allow to enter a date < than 01-01-1970)

And the condition was successfully created: 
https://conditional-tokens-explorer.dev.gnosisdev.com/#/conditions/0x5571136da50dd0ae6f76975d422f67acc801597422342ba94b5a74506856203b

**Expected result:** 
do not allow to create the same questions? 
I'm not sure..

### LINKED ISSUE #436: Prepare Omen condition: All the fields on the form should have the same validation rules
See the pic: while the reporting address field shows that the field is required when it is empty, the rest ones - do not.

**Expected Result:** All the fields on the form should have the same validation rules

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #408 
Closes #410 
Closes #428 
Closes #392 
Closes #430 
Closes #436 
Closes #435 

For the condition List, we can se this gif:

Peek 08-10-2020 16-12

For the prepare condition section, now we use the realitio oracle address, the input is readonly. Also fixed all the issues related to this omen prepare condition that we can see in the description
Peek 08-10-2020 16-15

----

I added the validity filter to this issue https://github.com/gnosis/conditional-tokens-explorer/issues/409
Also, I removed the `All` option to search, because we need to improve some things in thegraph, I will create an issue for this in the thegraph repository and in this repo to improve search. At this moment we can only search for the entire hash

----

Also, I removed the option from the _dropdown actions_ called `report payout`, if the condition was already resolved

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
I added the validity filter to this issue https://github.com/gnosis/conditional-tokens-explorer/issues/409
Also, I removed the `All` option to search, because we need to improve some things in thegraph, I will create an issue for this in the thegraph repository and in this repo to improve search. At this moment we can only search for the entire hash

**Comment by mariano-aguero** [comment]
Also, I removed the option from the _dropdown actions_ called `report payout`, if the condition was already resolved

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

File: src/components/filters/ConditionTypeFilterDropdown/index.tsx [hunk 1]
```diff
@@ -4,36 +4,40 @@ import { ButtonSelectLight } from 'components/buttons/ButtonSelectLight'
...
 import { FilterDropdown } from 'components/pureStyledComponents/FilterDropdown'
 import { FilterTitle } from 'components/pureStyledComponents/FilterTitle'
+import { useWeb3ConnectedOrInfura } from 'contexts/Web3Context'
 import { ConditionType, ConditionTypeAll } from 'util/types'
 
 interface Props {
-  onClick: (value: ConditionType | ConditionTypeAll) => void
-  value: string
+  onClick: (value: ConditionType | ConditionTypeAll, filter: Maybe<string>) => void
+  value: Maybe<string>
```
Comment (hpmaxi) [inline src/components/filters/ConditionTypeFilterDropdown/index.tsx:12]: filter and value types could be more narrow?

File: src/components/filters/ConditionTypeFilterDropdown/index.tsx [hunk 2]
```diff
@@ -4,36 +4,40 @@ import { ButtonSelectLight } from 'components/buttons/ButtonSelectLight'
...
 }
 
 export const ConditionTypeFilterDropdown: React.FC<Props> = (props) => {
+  const { networkConfig } = useWeb3ConnectedOrInfura()
   const { onClick, value } = props
 
+  const oracleRealitio = networkConfig.getOracleFromName('realitio' as KnownOracle)
+
```
Comment (hpmaxi) [inline src/components/filters/ConditionTypeFilterDropdown/index.tsx:20]: This could use `useMemo` with networkConfig as dependency.

File: src/components/filters/DateFilter/index.tsx [hunk 3]
```diff
@@ -35,34 +37,81 @@ const FieldWrapper = styled.div`
...
+    setFrom(fromTimestamp)
+  }
+
+  const onChangeToInternal = (event: React.ChangeEvent<HTMLInputElement>) => {
+    if (typeof onChangeTo === 'function') {
+      onChangeTo(event)
+    }
+
+    const toDateMoment = moment(event.currentTarget.value)
+    const toTimestamp = toDateMoment.unix()
```
Comment (hpmaxi) [inline src/components/filters/DateFilter/index.tsx:74]: This could be changed to make all the conversion without using extra variables, `moment(...).unix()` but also moved to a helper wich make explicit in his name what you are doing, `dateToTheGraphFormat`.

File: src/components/filters/DateFilter/index.tsx [hunk 4]
```diff
@@ -35,34 +37,81 @@ const FieldWrapper = styled.div`
...
+  React.useEffect(() => {
+    if (!from || !to) onSubmit(0, 0)
+  }, [from, to, onSubmit])
+
+  const errorMessage = React.useMemo(
+    () => (to && from && to < from ? 'To should be greater than From' : null),
+    [from, to]
+  )
+  const emptyValues = !from || !to
+
```
Comment (hpmaxi) [inline src/components/filters/DateFilter/index.tsx:93]: (This also applies to min, max).
emptyValues can be wrapped in `useMemo` and use in the effect leveraging morgan's law. It would be `if(!emptyValues) ... ` .

**Review by gabitoesmiapodo — CHANGES_REQUESTED** [review]
Good job, this makes using the app way easier.

❌   #410 works very well for the most part, but:

- We should do something about the Reporter / Oracle filter "Current Wallet"'s option. We could ask the user to connect, or we can disable the option. Related to this, if the user is not connected, selects "Current Wallet" and connects afterwards, no results are displayed (table is not updated).
- Number of outcomes (I know this was not specified...): If the user fills `Min` only, we should show anything above `Min`. And if they fill `Max` only, we should show anything below `Max`. It shouldn't be necessary to fill both inputs.
- The same goes for Creation Date, or any other range for that matter. 
- Hiding the filters' column should clear the filters.

Also we could probably come up with a better way to clear individual filters, though. Maybe later...

❌   #430 "Prepare" button is still enabled when there are 0 or 1 outcomes. It should be disabled.

> Expected Result: 'Prepare' button is disabled. user is not allowed to create a condition with 1 outcome

I added a note below the outcomes' list to make it more clear.

Also, we should make the min / max outcomes part of the `.env` vars (they're hardcoded in a few places now).

❌  #435 This works fine, but:

"Question must not exist" is not clear enough, the user will probably not know what we're talking about.

Probably we should use the warning component (see "Merge Positions" when using a resolved condition), something like:

**Title:** "Duplicated Question"
**Text:** "The question for this condition already exists on [ORACLE HERE]. Please change it to a different one."

🆗  #408
🆗  #428
🆗  #392
🆗  #436

File: src/config/networkConfig.ts [hunk 5]
```diff
@@ -365,6 +365,23 @@ export class NetworkConfig {
...
+    }
+
+    return {
+      name: 'unknown',
+      description: 'Unknown',
+      url: '',
+      address: '',
+    }
+  }
+
```
Comment (hpmaxi) [inline src/config/networkConfig.ts:384]: If unknown oracle is named `unknownOracle` thsi could also be written like
`networks[this.networkId].oracles.find(o => oracle.name === oracleName) || unknownOracle`, to me is shorter and clearer but is a matter of taste, so take it with a grain of salt

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

File: src/hooks/useConditionsList.tsx [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+    Status,
+    TextToSearch,
+  } = advancedFilter
+
+  const query = buildQueryConditionsList(advancedFilter)
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  const variables: { [k: string]: any } = {}
+  if (ReporterOracle.type === OracleFilterOptions.Custom)
+    variables['oracleNotIn'] = ReporterOracle.value
+  if (
```
Comment (hpmaxi) [inline src/hooks/useConditionsList.tsx:25]: There must be a better way to build queries and variables, but for the moment this should be accompanied with a test at least. About the type of variables, we can use `[k in someType]: anotherType` , if both types are generic we have a `Record`, I found that it is better to have only some valid keys in variables.

**Review by hpmaxi — APPROVED** [review]

File: src/components/filters/ConditionTypeFilterDropdown/index.tsx (hunk 1 above)
Comment (mariano-aguero) [reply src/components/filters/ConditionTypeFilterDropdown/index.tsx:12]: I think no

File: src/components/filters/ConditionTypeFilterDropdown/index.tsx (hunk 2 above)
Comment (mariano-aguero) [reply src/components/filters/ConditionTypeFilterDropdown/index.tsx:20]: Done

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

File: src/components/filters/DateFilter/index.tsx (hunk 3 above)
Comment (mariano-aguero) [reply src/components/filters/DateFilter/index.tsx:74]: looking in the code, this is the only place where something similar is used. I think at the moment it doesn't make sense

File: src/components/filters/DateFilter/index.tsx (hunk 4 above)
Comment (mariano-aguero) [reply src/components/filters/DateFilter/index.tsx:93]: Done!

File: src/config/networkConfig.ts (hunk 5 above)
Comment (mariano-aguero) [reply src/config/networkConfig.ts:384]: Mmm I will not do this, as you say is a matter of taste

File: src/hooks/useConditionsList.tsx (hunk 6 above)
Comment (mariano-aguero) [reply src/hooks/useConditionsList.tsx:25]: I didn't find any other solution or a queryBuilder or a solution that the library gives me.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by mariano-aguero** [comment]
> Good job, this makes using the app way easier.
> 
>  #410 works very well for the most part, but:
> 
> * We should do something about the Reporter / Oracle filter "Current Wallet"'s option. We could ask the user to connect, or we can disable the option. Related to this, if the user is not connected, selects "Current Wallet" and connects afterwards, no results are displayed (table is not updated).
> * Number of outcomes (I know this was not specified...): If the user fills `Min` only, we should show anything above `Min`. And if they fill `Max` only, we should show anything below `Max`. It shouldn't be necessary to fill both inputs.
> * The same goes for Creation Date, or any other range for that matter.
> * Hiding the filters' column should clear the filters.
> 
> Also we could probably come up with a better way to clear individual filters, though. Maybe later...
> 
>  #430 "Prepare" button is still enabled when there are 0 or 1 outcomes. It should be disabled.
> 
> > Expected Result: 'Prepare' button is disabled. user is not allowed to create a condition with 1 outcome
> 
> I added a note below the outcomes' list to make it more clear.
> 
> Also, we should make the min / max outcomes part of the `.env` vars (they're hardcoded in a few places now).
> 
>  #435 This works fine, but:
> 
> "Question must not exist" is not clear enough, the user will probably not know what we're talking about.
> 
> Probably we should use the warning component (see "Merge Positions" when using a resolved condition), something like:
> 
> **Title:** "Duplicated Question"
> **Text:** "The question for this condition already exists on [ORACLE HERE]. Please change it to a different one."
> 
>  #408
>  #428
>  #392
>  #436

Nice feedback! 

I finish with everything

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr443--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Great changes! 
I also I have reviewed the implemented features and have some notes (besides the listed above): 
1. Once a Redeem position option is removed for a resolved condition in the list, it would be nice to remove is from a position details as well
2. #408: Search returns an odd error when search by QuesitonID/Oracle Address/Creator Address and fill in the search field with numbers
error
3. #410: GraphQL fails when I perform 3 or more search queries =)
3-4 seqrch queries
4. #410: Column names overlap each other when filter is opened
opened filters
5. #430: It would be nice to show a warning message after filling in the 1st outcome rather then after filling in the Question field (from me perspective, every red message looks a bit scaring for a user, especially when a form is not completely filled it)
6. #435 : still do not see any warning message, even if I create the same condition within an hour. =(
7. #392 : looks like a resolution date is completely removed from a condition details. is it an expected behavior?


Look good: 
#436 
#428 

Also, a lot of the issues reported in #440 are fixed (marked them as fixed there). However, several ones are still unfixed, I made them in bold. It would be nice to take a look into them as well. 

Thanks a lot!

**Review by gabitoesmiapodo — APPROVED** [review]
- 🆗  We should do something about the Reporter / Oracle filter "Current Wallet"'s option (...) -> There's a small problem with this, I created an issue here: 
- 🆗  Number of outcomes (I know this was not specified...) (...) -> Added `onPressEnter` to this.
- 🆗  The same goes for Creation Date, or any other range for that matter. (...) -> Added `onPressEnter` to this.
- 🆗  Hiding the filters' column should clear the filters.
- 🆗  #430 "Prepare" button is still enabled when there are 0 or 1 outcomes. It should be disabled. (...) -> I removed the error message, seems redundant when having a note stating the rules for this.
- 🆗  Also, we should make the min / max outcomes part of the .env vars (...)
- 🆗  "Question must not exist" is not clear enough, (...)

**Comment by mariano-aguero** [comment]
> Great changes!
> I also have reviewed the implemented features and have some notes (besides the listed above):
> 
> 1. Once a Redeem position option is removed for a resolved condition in the list, it would be nice to remove it from a position details as well

I removed the report payout option, not the redeem option. I opened an issue for this https://github.com/gnosis/conditional-tokens-explorer/issues/458


> 4. #410: Column names overlap each other when filter is opened
>    opened filters

Created an issue for this https://github.com/gnosis/conditional-tokens-explorer/issues/459

> 7. #392 : looks like a resolution date is completely removed from a condition details. is it an expected behavior?

Yes, is remove it when the condition is not resolved, because there is no timestamp

**Comment by mariano-aguero** [comment]
@elena-zh can you create issues for every error that you catch ? I really appreciate it 
If you can't, please let me know

**Comment by elena-zh** [comment]
@mariano-aguero , tasks for pp.1, 4 ,7 were created by you, thanks. 
I have create a separate ticket for p.2 - #467, for p.6 - reopened #435.
pp. 3, 5 are not reproducible so far.
