### PR TITLE
[FE] Fix sorting in conditions and positions tabs

### LINKED ISSUE #340: [FE] Fix sorting in conditions and positions tabs
It's not immediately obvious what order the items in the conditions and positions tabs are sorted in.
As a new user, I would assume they are sorted in reverse chronological order, newest first. When, in fact, they are sorted in ascending order by condition ID.

Condition ID is a pseudorandom hash, so it's meaningless to sort them in descending order.

This brings up an interesting issue. There are five columns currently in the conditions tab and sorting by any of them is pretty meaningless (at least without [richer search](https://github.com/gnosis/conditional-tokens-explorer/issues/337)).

In the conditions tab, we should:
1. disable sorting by conditionID, reporting address, and question ID.
2. add a "creation date" column and default to sorting the list by creation date in reverse chronological order.
3. add a total value locked (TVL) column and enable sorting by this column.
4. add an "oracle" column

In the positions tab, we should:
1. disable sorting by position ID
2. add a "creation date" column and default to sorting the list by creation date in reverse chronological order.
3. add an "oracle" column
4. add a "condition" ID column
5. add a "question ID" column

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #340 

We can't add ` total value locked (TVL) `

Please check when a position have multiple conditions related. I added a more button, but I don't like it... Feedback welcome

### CODE REVIEW

File: src/components/filters/DateFilter/index.tsx [hunk 1]
```diff
@@ -77,7 +77,7 @@ export const DateFilter: React.FC<Props> = (props) => {
         onChangeTo(event)
       }
 
-      const toDateMoment = moment(event.currentTarget.value).utc().add(24, 'hours')
+      const toDateMoment = moment(event.currentTarget.value).utc().endOf('day')
       const toTimestamp = toDateMoment.unix()
```
Comment (mariano-aguero) [inline src/components/filters/DateFilter/index.tsx:81]: Fix when we filter by date. Now we can filter in this way, for example
To: 16/10/2020 00:00:01
From: 16/10/2020 23:59:59

File: src/pages/PositionsList/index.tsx [hunk 2]
```diff
@@ -297,6 +319,124 @@ export const PositionsList = () => {
...
+        cell: (row: PositionWithUserBalanceWithDecimals) => {
+          const { conditions } = row
+          const questionId = conditions[0]?.questionId ?? ''
+          if (conditions.length === 1) {
+            return <Hash value={questionId} />
+          } else {
+            return (
+              <>
+                <Hash value={questionId} />
+                <MoreLink
```
Comment (mariano-aguero) [inline src/pages/PositionsList/index.tsx:414]: We display a more link button, just in case exist more than one condition, should exist more than one oracle. I don't like this, maybe exist a better way to do this (same for question Id)

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr493--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
@mariano-aguero , conditions grid looks fine. 
The only thing that I would like to fix there is an arrow placement for the Creation Date column (from right side to the left side, like it is implemented for the rest columns). Also, it would be nice to always show it to let a user know the current sort order. 


As for the Positions list.. Here are my notes: 
1. The grid has become scrollable because of a huge amount of columns there... And it is not obviously, especially when more that 10 items per page are shown.  It seems to be closer to design issue, though. @gabitoesmiapodo , could you please suggest something?=)
2. 'More' button for the Oracle field  may open a grid with 2 the same oracles. Is there is a possibility to hide it when position has 2 conditions with the same oracle? 
3. the last grid line is missing when scroll grid 

4. Move the filter icon from the left side to the right side for the ERC amounts columns (the same as for the creation date column in the conditions list)
5. IMHO, it would be nice to move the 'Creation Date' column to be displayed as the 1st one in both Conditions and Positions grids (according to the default sort order). @gabitoesmiapodo , what do you think?

**Review by hpmaxi — APPROVED** [review]

**Review by gabitoesmiapodo — APPROVED** [review]
@elena-zh there's a semi related issue for the sort arrow here https://github.com/gnosis/conditional-tokens-explorer/issues/281, but it's not a really important issue now (and I still don't know why that happens).

I agree with the fact that probably we should always show the arrows, but I don't think there's a setting for that. We could  investigate this later.

> As for the Positions list.. Here are my notes:

1. _The grid has become scrollable (...)_ I don't think there's much we can do here, besides showing less columns (which is what I would do, we have the "details" section to see every detail). Anyways, no easy fix here, tables are always a hassle. Maybe we can think of something better later?
2. _More' button for the Oracle field (...)_ agreed.
3. _ Maybe I can add a top border to the table's footer later.
4. _Move the sort arrow from the left side to the right side for the ERC amounts columns (...)_ Same as 1.
5. _IMHO, it would be nice to move the 'Creation Date' (...)_ Not sure about how important the date is, maybe we should ask. I'd leave it as the last column if it was my call, but I don't know.

@mariano-aguero 

_We display a more link button, just in case exist more than one condition (...)_ we can make a better link / button later (or even a sub table or something else), I think this  is all right for now.

See Elena's suggestions above, this is good enough for me ATM.

**Comment by elena-zh** [comment]
@gabitoesmiapodo ,thank you! And as for
`Maybe we can think of something better later?`

I would like to suggest whether 'show/hide' columns functionality or 'collapse/expand'..
As another option,  implement a dropdown which contains checkboxes with a list of columns a user can select to display (+to show 3-4 columns by default). 

But agree. Let think about it a bit later.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr493--conditionaltokensexplorer.review.gnosisdev.com

**Comment by elena-zh** [comment]
Verified and the changes look good to me in Dev. 
I have created several related issues: 
#499 - here I have mentioned all the UI issues with Positions/Conditions lists
#500  - low priority enhancement about implementation an ability to 'show/hide' columns or 'collapse/expand' in the Positions/Conditions lists
