### PR TITLE
Fix integration with custom tokens

### LINKED ISSUE #140: [FE] Issues - Add custom collateral
@mariano-aguero add definition

### PR DESCRIPTION
**Pull request by hpmaxi**
Closes #140 

`collateralToken` is used for the `Token` object and `collateral` for the string. Is all managed by react-hook-form until the first component that fetch the token for an address and append it to the tokens list passed to the select component.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr152--conditionaltokensexplorer.review.gnosisdev.com

File: src/pages/SplitPosition/index.tsx [hunk 1]
```diff
@@ -47,15 +49,23 @@ export const SplitPosition = () => {
...
       }
     },
-    [status, CTService, connect, collateralToken]
+    [status, CTService, connect]
   )
 
+  // TODO Fix this
+  if (!collateralToken) {
+    return null
+  }
```
Comment (lmcorbalan) [inline src/pages/SplitPosition/index.tsx:58]: Is this a missing TODO?

Comment (hpmaxi) [reply src/pages/SplitPosition/index.tsx:58]: No, it is not. But I wanted to check for null (and reuse `useCollateral` that returns a Maybe) to avoid doing that in subcomponents. Maybe another option is to throw an error or log something.

**Comment by gabitoesmiapodo** [comment]
Seems to work, added a few weird custom tokens and all work fine.

We're missing some styling here, but I'll fix that on https://github.com/gnosis/conditional-tokens-explorer/issues/71

File: src/components/form/SelectCollateral/index.tsx [hunk 2]
```diff
@@ -41,8 +40,13 @@ export const SelectCollateral = ({
   })
 
   useEffect(() => {
-    onCollateralChange(watchCollateral)
-  }, [watchCollateral, onCollateralChange])
+    const token = tokens.find((t) => t.address === watchCollateral)
+    if (token) {
+      setCollateral(token.symbol)
+    } else {
+      console.error('Unknown token', watchCollateral)
```
Comment (mariano-aguero) [inline src/components/form/SelectCollateral/index.tsx:47]: Use logger

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr152--conditionaltokensexplorer.review.gnosisdev.com
