### PR TITLE
(fix) remove number input spinners on firefox

### LINKED ISSUE #607: Firefox - UI: Number Of Outcomes filter fields contain arrows which overlap placeholders
See the pic

The issue is applicable only to **FireFox**

**Expected Result:** 

However, if it is impossible to remove the arrows from the fields, it would be nice to adjust them (or placeholders) in order not to overlap each other

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #607

It should look like this now on Firefox.

Screen Shot 2020-11-12 at 17 07 36

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr609--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]

File: src/components/filters/MinMaxFilter/index.tsx [hunk 1]
```diff
@@ -7,13 +7,14 @@ import { FilterTitle } from 'components/pureStyledComponents/FilterTitle'
 import { Textfield } from 'components/pureStyledComponents/Textfield'
 import { MAX_OUTCOMES_ALLOWED, MIN_OUTCOMES_ALLOWED } from 'config/constants'
 
-const Wrapper = styled.div``
+const Wrapper = styled.div`
+  /* margin-bottom: 8px; */
```
Comment (mariano-aguero) [inline src/components/filters/MinMaxFilter/index.tsx:11]: Mmmm why this line is commented ? can we remove it ?

**Comment by elena-zh** [comment]
Looks good to me!
