### PR TITLE
(Fix) Status info window's width

### LINKED ISSUE #454: Make modal's for reject the transaction in Metamask width narrower
Related to the cases: 
  - wrap collateral - reject
  - unwrap collateral - reject
 - transfer outcome tokens - reject

**Expected Result:** 
make the modal's width like it is for the actions described in #342

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #454

- Wrap Collateral - reject / Unwrap collateral - reject / Transfer outcome tokens - reject: All of the status info windows' widths should be correct now.
- Users can use the enter key in the wrap / unwrap modals to submit the form now. We could do the same for other forms later, if it makes sense.
- Fixed a nested button console error.

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr456--conditionaltokensexplorer.review.gnosisdev.com

File: src/components/modals/UnwrapModal/index.tsx [hunk 1]
```diff
@@ -53,6 +53,28 @@ export const UnwrapModal: React.FC<Props> = (props) => {
...
+    if (isSubmitDisabled) return
+
+    onUnWrap(unWrapValues)
+
+    if (onRequestClose) onRequestClose(e)
+  }
+
+  const onPressEnter = (e: React.KeyboardEvent<HTMLInputElement>) => {
+    if (e.key === 'Enter') unWrap(e)
+  }
```
Comment (hpmaxi) [inline src/components/modals/UnwrapModal/index.tsx:76]: Render a button is cheap, but anyways...you can wrap `unwrap` in a `useCallback` hook, but it's ok without doing it

**Review by hpmaxi — APPROVED** [review]

File: src/components/modals/UnwrapModal/index.tsx (hunk 1 above)
Comment (gabitoesmiapodo) [reply src/components/modals/UnwrapModal/index.tsx]: Adding `useCallback` was even cheaper. Fixed.

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 https://pr456--conditionaltokensexplorer.review.gnosisdev.com

**Review by mariano-aguero — APPROVED** [review]

**Comment by elena-zh** [comment]
Verified. 
Just to notice:  enter key in the wrap / unwrap modals to submit the form works only in the case when a cursor is displayed in the Amount field. When fill in the Amount field using 'Use Position Balance' action button,  enter key doesn't work.
